name: Test installing @enterthenamehere/esdoc package globally
on:
  workflow_dispatch:

jobs:
  test-installation:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        node-version: [14]
        os: [ubuntu-latest]
        package-manager: [npm]
        package-number: [1, 2, 3]
    
    runs-on: ${{matrix.os}}
    steps:
    - name: "Use ${{matrix.node-version}} Node.js on ${{matrix.os}}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.version}}
    
    - name: "Install @enterthenamehere/esdoc package group ${{matrix.package-number}} globally"
      run: |
        ${{matrix.package-manager}} run prepare-global-test${{matrix.package-number}}-${{matrix.package-manager}}
    
    - name: "Checkout repository with tests"
      uses: actions/checkout@v2

    - name: "Run test with global esdoc"
      working-directory: ./test/fixture
      run: |
        esdoc --debug --verbose
        echo "printing out/index.json"
        cat out/index.json
    
    - name: "Run unit-test"
      run: |
        ${{matrix.package-manager}} run global-test-${{matrix.package-manager}}
