name: Test global installation
on:
  workflow_dispatch:
    inputs:
      runOn:
        description: 'Run on:'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - 'ubuntu-latest'
        - 'macos-latest'
        - 'windows-latest'
      nodeVersion:
        description: 'Node.js version:'
        required: true
        default: '14'
        type: choice
        options:
        - '14'
        - '16'
        - 'latest'
      testNumber:
        description: 'Which test to run:'
        required: true
        default: '02'
        type: choice
        options:
        - '01'
        - '02'
        - '03'
      packageManager:
        description: 'Which package manager to use:'
        required: true
        default: 'npm'
        type: choice
        options:
        - 'npm'
        - 'yarn'
        - 'pnpm'
    

jobs:
  test-installation:
    runs-on: ${{github.event.inputs.runOn}}
    steps:
    - name: "Setting up Node.js ${{github.event.inputs.nodeVersion}} on ${{github.event.inputs.runOn}}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{github.event.inputs.nodeVersion}}

    - name: "Checkout repository with tests"
      uses: actions/checkout@v3
    
    - name: "Installing packages for test ${{github.event.inputs.testNumber}}"
      run: |
        ${{github.event.inputs.packageManager}} run global-test-${{github.event.inputs.testNumber}}-install-packages-${{github.event.inputs.packageManager}}

    - name: "Listing installed packages"
      run: |
        ${{github.event.inputs.packageManager}} run global-list-packages-${{github.event.inputs.packageManager}}

    - name: "Run esdoc globally to generate documentation"
      working-directory: ./test/fixtures/${{github.event.inputs.testNumber}}/
      run: |
        esdoc
    
    - name: "Installing testing suite"
      run: |
        ${{github.event.inputs.packageManager}} run install-testing-suite-${{github.event.inputs.packageManager}}
    
    - name: "Run unit tests for fixture ${{github.event.inputs.testNumber}}"
      run: |
        ${{github.event.inputs.packageManager}} run global-test-${{github.event.inputs.testNumber}}
