name: Test installing @enterthenamehere/esdoc package locally
on:
  workflow_dispatch:

jobs:
  test-installation:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        node-version: [14, 16, latest]
        os: [ubuntu-latest, macos_latest, windows_latest]
        package-manager: [npm]
        test-number: [1, 2, 3]
    
    runs-on: ${{matrix.os}}
    steps:
    - name: "Use ${{matrix.node-version}} Node.js on ${{matrix.os}}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.version}}
      
    - name: "Checkout repository with tests"
      uses: actions/checkout@v3
    
    - name: "Run installation script for test ${{matrix.test-number}} with ${{matrix.package-manager}}"
      working-directory: ./test/fixture
      run: |
        ${{matrix.package-manager}} run local-test${{matrix.test-number}}${{matrix.package-manager}}

    - name: "Generate documentation with local esdoc"
      working-directory: ./test/fixture
      run: |
        ${{matrix.package-manager}} exec @enterthenamehere/esdoc --debug --verbose
        echo "printing out/index.json"
        cat out/index.json
    
    - name: "Run unit test ${{matrix.test-number}}"
      run: |
        ${{matrix.package-manager}} run local-test${{matrix.test-number}}
