name: Test global installation
on:
  workflow_dispatch:

jobs:
  test-installation:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos_latest, windows_latest]
    
    runs-on: ${{matrix.os}}
    steps:
    - name: "Use 16 Node.js on ${{matrix.os}}"
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: "Checkout repository with tests"
      uses: actions/checkout@v3
    
    - name: "Install @enterthenamehere/esdoc package group 1 globally"
      run: |
        npm run prepare-global-test1-npm
    
    - name: "Run test with global esdoc"
      working-directory: ./test/fixture
      run: |
        esdoc --debug --verbose
        echo "printing out/index.json"
        cat out/index.json
    
    - name: "Run unit-test"
      run: |
        npm run global-test-npm
    
    - name: Remove generated documentation
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./test/fixture/out
    


    - name: "Install @enterthenamehere/esdoc package group 2 globally"
      run: |
        npm run prepare-global-test2-npm
    
    - name: "Run test with global esdoc"
      working-directory: ./test/fixture
      run: |
        esdoc --debug --verbose
        echo "printing out/index.json"
        cat out/index.json
    
    - name: "Run unit-test"
      run: |
        npm run global-test-npm
    
    - name: Remove generated documentation
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./test/fixture/out
    


    - name: "Install @enterthenamehere/esdoc package group 3 globally"
      run: |
        npm run prepare-global-test1-npm
    
    - name: "Run test with global esdoc"
      working-directory: ./test/fixture
      run: |
        esdoc --debug --verbose
        echo "printing out/index.json"
        cat out/index.json
    
    - name: "Run unit-test"
      run: |
        npm run global-test-npm
