name: Test
on:
  workflow_dispatch:

jobs:
  test-installation:    
    runs-on: ubuntu-latest
    steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: 14
      
    - name: "Install latest @enterthenamehere/esdoc and @enterthenamehere/esdoc-standard-plugin globally"
      run: npm install -g @enterthenamehere/esdoc@dev @enterthenamehere/esdoc-standard-plugin@dev
    
    - name: "Get npm global path"
      run: npm config get prefix
    
    - name: "list packages"
      run: npm list @enterthenamehere --global --depth=3
